# rocks-dev
[dev]
path = "~/Develop/Nvim"


# rocks-config
[config]
auto_setup = true
colorscheme = "sweetie"


# rocks-treesitter
[treesitter]
auto_highlight = "all"
auto_install = false


# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]


# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.44.0"
"rocks-git.nvim" = "2.5.3"
"rocks-dev.nvim" = "1.7.0"
"rocks-edit.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
"rocks-config.nvim" = "3.1.0"
"rocks-treesitter.nvim" = "1.3.0"
"sweetie.nvim" = { version = "3.2.0", colorscheme = "sweetie" }
neorg = { version = "9.3.0", ft = "norg" }
neorg-conceal-wrap = "1.0.1"
"daylight.nvim" = { version = "1.1.0", event = "ColorScheme" }
"telescope.nvim" = { version = "scm", cmd = "Telescope" }
"telescope-file-browser.nvim" = "scm"
# "telescope-zf-native.nvim" = "1.0.0"  # FIXME: can't compile on NixOS
nvim-web-devicons = "0.100"
"numb.nvim" = { version = "scm", event = "CmdlineEnter" }
"zen-mode.nvim" = { version = "1.4.0", cmd = "ZenMode" }
"which-key.nvim" = { version = "2.1.0", pin = true, cmd = "WhichKey" }
"auto-hlsearch.nvim" = { version = "1.1.0", event = "CmdlineEnter" }
"neogit" = { version = "scm", cmd = "Neogit" }
"paperplanes.nvim" = { version = "0.1.6", cmd = "PP" }
nvim-notify = "3.15.0"
rustaceanvim = "6.0.1"
"venn.nvim" = { version = "scm", cmd = "VBox" }
"hlchunk.nvim" = { version = "1.3.0", event = "DeferredUIEnter" }
"twilight.nvim" = "1.0.0"
friendly-snippets = "scm"
nvim-treesitter-legacy-api = "0.9.2"
"cord.nvim" = "2.2.3"
"oil.nvim" = "2.15.0"
"sense.nvim"= "1.0.1"
nvim-surround = "3.1.0"

# tree-sitter parsers
tree-sitter-zig = "scm"
tree-sitter-lua = "scm"
tree-sitter-luadoc = "scm"
tree-sitter-json = "scm"
tree-sitter-toml = "scm"
tree-sitter-fish = "scm"
tree-sitter-html = "scm"
tree-sitter-css = "scm"
tree-sitter-jsdoc = "scm"
tree-sitter-javascript = "scm"
tree-sitter-typescript = "scm"
tree-sitter-vim = "scm"
tree-sitter-elixir = "0.0.41"
tree-sitter-rust = "scm"
tree-sitter-comment = "scm"
tree-sitter-bash = "scm"
tree-sitter-nix = "scm"
tree-sitter-nickel = "scm"
tree-sitter-ecma = "scm"
tree-sitter-just = "scm"
tree-sitter-svelte = "0.0.33"
tree-sitter-sql = "0.0.40"
tree-sitter-kdl = "0.0.30"
tree-sitter-yaml = "0.0.32"
tree-sitter-jinja = "0.0.6"
tree-sitter-ron = "0.0.29"

[plugins."gitsigns.nvim"]
git = "github:lewis6991/gitsigns.nvim"
rev = "v1.0.2"

[plugins."visual-whitespace.nvim"]
git = "github:mcauley-penney/visual-whitespace.nvim"
rev = "e22d8508a0236f274dde39775ee127c85d30c0c0"
event = "DeferredUIEnter"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v1.1.1"

[plugins."tabline-framework.nvim"]
git = "rafcamlet/tabline-framework.nvim"
rev = "f0d229cc2c103bbc356d26c928eff02be40b230f"

[plugins.nvim-autopairs]
git = "windwp/nvim-autopairs"
rev = "b464658e9b880f463b9f7e6ccddd93fb0013f559"

[plugins.showkeys]
git = "nvzone/showkeys"
rev = "8daf5abb5fece0c9e1fa2c5679aaf226a80f5c38"

[plugins."nvim-colorizer.lua"]
git = "catgoose/nvim-colorizer.lua"
rev = "517df88cf2afb36652830df2c655df2da416a0ae"
