# rocks-dev
[dev]
path = "~/Develop/Nvim"


# rocks-config
[config]
auto_setup = true
colorscheme = "sweetie"


# rocks-treesitter
[treesitter]
auto_highlight = "all"
auto_install = false


# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]


# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.45.0"
"rocks-git.nvim" = "2.5.3"
"rocks-dev.nvim" = "1.8.0"
"rocks-edit.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
"rocks-config.nvim" = "3.1.1"
"rocks-treesitter.nvim" = "1.3.0"
"sweetie.nvim" = { version = "3.2.0", colorscheme = "sweetie" }
neorg = { version = "9.3.0", ft = "norg" }
neorg-conceal-wrap = "1.0.1"
"daylight.nvim" = { version = "1.1.0", event = "ColorScheme" }
nvim-web-devicons = "0.100"
"numb.nvim" = { version = "scm", event = "CmdlineEnter" }
"which-key.nvim" = { version = "2.1.0", pin = true, cmd = "WhichKey" }
"auto-hlsearch.nvim" = { version = "1.1.0", event = "CmdlineEnter" }
# "neogit" = { version = "scm", cmd = "Neogit" }
"paperplanes.nvim" = { version = "0.1.6", cmd = "PP" }
nvim-notify = "3.15.0"
rustaceanvim = "6.3.0"
"venn.nvim" = { version = "scm", cmd = "VBox" }
"hlchunk.nvim" = { version = "1.3.0", event = "DeferredUIEnter" }
friendly-snippets = "scm"
nvim-treesitter-legacy-api = "0.9.2"
"cord.nvim" = { version = "2.2.7", event = "DeferredUIEnter" }
"oil.nvim" = { version = "2.15.0", cmd = "Oil" }
"sense.nvim"= { version = "1.0.1", event = "DiagnosticChanged" }
nvim-surround = { version = "3.1.2", event = "DeferredUIEnter" }

# tree-sitter parsers
tree-sitter-zig = "0.0.34"
tree-sitter-lua = "0.0.35"
tree-sitter-luadoc = "0.0.29"
tree-sitter-json = "0.0.36"
tree-sitter-toml = "0.0.31"
tree-sitter-fish = "0.0.30"
tree-sitter-html = "0.0.36"
tree-sitter-css = "0.0.37"
tree-sitter-jsdoc = "0.0.35"
tree-sitter-javascript = "0.0.36"
tree-sitter-typescript = "0.0.37"
tree-sitter-vim = "0.0.34"
tree-sitter-elixir = "0.0.42"
tree-sitter-rust = "0.0.50"
tree-sitter-comment = "0.0.31"
tree-sitter-nix = "0.0.59"
tree-sitter-ecma = "0.0.30"
tree-sitter-svelte = "0.0.33"
tree-sitter-sql = "0.0.41"
tree-sitter-kdl = "0.0.30"
tree-sitter-yaml = "0.0.36"
tree-sitter-jinja = "0.0.7"
tree-sitter-heex = "0.0.34"
tree-sitter-vimdoc = "0.0.34"

[plugins."gitsigns.nvim"]
git = "github:lewis6991/gitsigns.nvim"
rev = "v1.0.2"
event = "DeferredUIEnter"

[plugins."visual-whitespace.nvim"]
git = "github:mcauley-penney/visual-whitespace.nvim"
rev = "e22d8508a0236f274dde39775ee127c85d30c0c0"
event = "DeferredUIEnter"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v1.3.1"
event = "DeferredUIEnter"

[plugins."tabline-framework.nvim"]
git = "rafcamlet/tabline-framework.nvim"
rev = "f0d229cc2c103bbc356d26c928eff02be40b230f"

[plugins.nvim-autopairs]
git = "windwp/nvim-autopairs"
rev = "b464658e9b880f463b9f7e6ccddd93fb0013f559"
event = "InsertEnter"

[plugins.showkeys]
git = "nvzone/showkeys"
rev = "8daf5abb5fece0c9e1fa2c5679aaf226a80f5c38"
cmd = "ShowKeysToggle"

[plugins."nvim-colorizer.lua"]
git = "catgoose/nvim-colorizer.lua"
rev = "517df88cf2afb36652830df2c655df2da416a0ae"
ft = ["css", "scss"]
cmd = ["ColorizerAttachToBuffer", "ColorizerDetachFromBuffer", "ColorizerReloadAllBuffers", "ColorizerToggle"]

[plugins."tint.nvim"]
git = "levouh/tint.nvim"
rev = "586e87f00c8b0f5e857cefe10839e41f3e8c6d01"
