# rocks-config
[config]
auto_setup = true
colorscheme = "sweetie"


# rocks-treesitter
[treesitter]
auto_highlight = "all"
auto_install = "prompt"


# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]


# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.36.1"
"rocks-git.nvim" = "2.0.1"
"rocks-dev.nvim" = "1.3.0"
"rocks-edit.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
"rocks-config.nvim" = "2.2.0"
"rocks-treesitter.nvim" = "1.0.3"
"sweetie.nvim" = { version = "3.1.1", colorscheme = "sweetie" }
neorg = { version = "9.1.1", ft = "norg" }
neorg-conceal-wrap = "1.0.0"
"daylight.nvim" = { version = "1.1.0", event = "BufWinEnter" }
"telescope.nvim" = { version = "scm", cmd = "Telescope" }
"telescope-file-browser.nvim" = "scm"
"telescope-zf-native.nvim" = "1.0.0"
nvim-web-devicons = "0.100"
"numb.nvim" = { version = "scm", event = "CmdlineEnter" }
"zen-mode.nvim" = { version = "1.4.0", cmd = "ZenMode" }
"which-key.nvim" = { version = "2.1.0", pin = true, cmd = "WhichKey" }
"tabby.nvim" = { version = "2.5.1", event = [ "TabNewEntered" ] }
"auto-hlsearch.nvim" = { version = "1.1.0", event = "CmdlineEnter" }
"neogit" = { version = "scm", cmd = "Neogit" }
"paperplanes.nvim" = { version = "0.1.6", cmd = "PP" }
"mini.surround" = { version = "0.9.0", event = "DeferredUIEnter" }
"mini.pairs" = { version = "0.9.0", event = [ "InsertEnter", "CmdlineEnter" ] }
nvim-notify = "3.13.5"
rustaceanvim = "5.1.1"
"venn.nvim" = { version = "scm", cmd = "VBox" }
"hlchunk.nvim" = { version = "1.1.0", event = "DeferredUIEnter" }
"care.nvim" = { version = "dev", event = "InsertEnter" }

# tree-sitter parsers
tree-sitter-zig = "0.0.2"
tree-sitter-lua = "0.0.2"
tree-sitter-luadoc = "0.0.2"
tree-sitter-json = "0.0.2"
tree-sitter-toml = "0.0.2"
tree-sitter-fish = "0.0.2"
tree-sitter-html = "0.0.2"
tree-sitter-css = "0.0.2"
tree-sitter-jsdoc = "0.0.2"
tree-sitter-javascript = "0.0.2"
tree-sitter-typescript = "0.0.3"
tree-sitter-vim = "0.0.2"
tree-sitter-elixir = "0.0.2"
tree-sitter-rust = "0.0.2"
tree-sitter-comment = "0.0.2"
tree-sitter-bash = "0.0.2"
tree-sitter-nix = "0.0.1"
nvim-treesitter-legacy-api = "0.9.2"

# rocks-git plugins
[plugins."lsp_lines.nvim"]
git = "sourcehut:whynothugo/lsp_lines.nvim"
rev = "v3.0.0^{}"

[plugins."gitsigns.nvim"]
git = "github:lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."visual-whitespace.nvim"]
git = "github:mcauley-penney/visual-whitespace.nvim"

[plugins.care-lsp]
git = "github:max397574/care-lsp"
