# rocks-config
[config]
auto_setup = true

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
lua-curl = "0.3.13"
mimetypes = "1.0.0"
xml2lua = "1.5"


# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.21.1"
"rocks-git.nvim" = "1.4.0"
"rocks-dev.nvim" = "1.1.2"
"rocks-config.nvim" = "1.4.0"
nvim-treesitter = "0.9.2"
"sweetie.nvim" = "2.4.0"
neorg = "8.0.0"
"daylight.nvim" = "1.1.0"
nvim-lspconfig = "0.1.7"
"telescope.nvim" = "scm"
nvim-possession = "0.0.13"
nvim-web-devicons = "0.99"
"numb.nvim" = "scm"
"zen-mode.nvim" = "1.3.0"
"which-key.nvim" = "1.6.0"
"tabby.nvim" = "2.3.1"
"auto-hlsearch.nvim" = "1.1.0"
"neogit" = "scm"
"paperplanes.nvim" = "0.1.6"
"neodev.nvim" = "2.5.2"
"twilight.nvim" = "1.0.0"
"mini.nvim" = "scm"
"lsp_signature.nvim" = "scm"
nvim-notify = "3.13.4"
"telescope-file-browser.nvim" = "scm"

# [plugins."rest.nvim"]
# dir = "~/Develop/Nvim/rest.nvim"

# rocks-git plugins
# [plugins."gentoo.vim"]
# git = "gentoo/gentoo-syntax"

# Telescope extensions
[plugins."telescope-zf-native.nvim"]
git = "github:natecraddock/telescope-zf-native.nvim"

# Better diagnostics
# [plugins."lsp_lines.nvim"]
# git = "sourcehut:~whynothugo/lsp_lines.nvim"

# Git signs for diff
[plugins."gitsigns.nvim"]
git = "github:lewis6991/gitsigns.nvim"

# GFM Markdown preview
[plugins."github-preview.nvim"]
git = "github:wallpants/github-preview.nvim"

# Visual mode whitespaces
[plugins."visual-whitespace.nvim"]
git = "github:mcauley-penney/visual-whitespace.nvim"
