# rocks-config
[config]
auto_setup = true
colorscheme = "sweetie"


# rocks-treesitter
[treesitter]
auto_highlight = "all"
auto_install = "prompt"


# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]


# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.31.1"
"rocks-git.nvim" = "1.5.1"
"rocks-dev.nvim" = "1.2.3"
"rocks-lazy.nvim" = "scm"
"rocks-config.nvim" = "2.0.0"
"rocks-treesitter.nvim" = "scm"
nvim-treesitter-legacy-api = "0.9.2"
"sweetie.nvim" = { version = "3.1.1", opt = true, colorscheme = "sweetie" }
neorg = { version = "8.7.1", opt = true, ft = "norg" }
"daylight.nvim" = { version = "1.1.0", opt = true, event = "BufWinEnter" }
nvim-lspconfig = { version = "0.1.8", opt = true, ft = [ "lua", "zig", "rust", "javascript", "typescript", "html", "css" ] }
"telescope.nvim" = { version = "scm", opt = true, cmd = "Telescope" }
"telescope-file-browser.nvim" = "scm"
nvim-web-devicons = "0.100"
"numb.nvim" = { version = "scm", opt = true, event = "CmdlineEnter" }
"zen-mode.nvim" = { version = "1.3.0", opt = true, cmd = "ZenMode" }
"which-key.nvim" = "2.1.0"
"tabby.nvim" = { version = "2.5.1", opt = true, event = [ "TabNewEntered" ] }
"auto-hlsearch.nvim" = { version = "1.1.0", opt = true, event = "CmdlineEnter" }
"neogit" = { version = "scm", opt = true, cmd = "Neogit" }
"paperplanes.nvim" = { version = "0.1.6", opt = true, cmd = "PP" }
"mini.nvim" = "scm"
"lsp_signature.nvim" = { version = "scm", opt = true, event = "LspAttach" }
nvim-notify = "3.13.5"
rustaceanvim = { version = "4.25.0", opt = true, ft = "rust" }
"venn.nvim" = { version = "scm", opt = true, cmd = "VBox" }

# tree-sitter parsers
tree-sitter-zig = "scm"
tree-sitter-lua = "scm"
tree-sitter-luadoc = "scm"
tree-sitter-json = "scm"
tree-sitter-toml = "scm"
tree-sitter-fish = "scm"
tree-sitter-html = "scm"
tree-sitter-css = "scm"
tree-sitter-jsdoc = "scm"
tree-sitter-javascript = "scm"
tree-sitter-typescript = "scm"
tree-sitter-vim = "scm"
tree-sitter-elixir = "scm"
tree-sitter-rust = "scm"
tree-sitter-comment = "scm"

# [plugins."rest.nvim"]
# dir = "~/Develop/Nvim/rest.nvim"
#
# [plugins."rocks-ui.nvim"]
# dir = "~/Develop/Nvim/rocks-ui.nvim"

# rocks-git plugins
# [plugins."gentoo.vim"]
# git = "gentoo/gentoo-syntax"

# Telescope extensions
[plugins."telescope-zf-native.nvim"]
git = "github:natecraddock/telescope-zf-native.nvim"

# Better diagnostics
[plugins."lsp_lines.nvim"]
git = "sourcehut:whynothugo/lsp_lines.nvim"
opt = true
event = "LspAttach"

# Git signs for diff
[plugins."gitsigns.nvim"]
git = "github:lewis6991/gitsigns.nvim"

# GFM Markdown preview
# [plugins."github-preview.nvim"]
# git = "github:wallpants/github-preview.nvim"

# Visual mode whitespaces
[plugins."visual-whitespace.nvim"]
git = "github:mcauley-penney/visual-whitespace.nvim"
