local _2afile_2a = "fnl/core/maps.fnl"
vim.g["mapleader"] = " "
vim.api.nvim_set_keymap("n", "<C-z>", "<Nop>", {})
vim.api.nvim_set_keymap("n", "Q", "<Nop>", {})
vim.api.nvim_set_keymap("n", ";", ":", {})
vim.api.nvim_set_keymap("n", "ww", "<cmd>w<cr>", {})
vim.api.nvim_set_keymap("n", "ZZ", "<cmd>wqa<cr>", {})
vim.api.nvim_set_keymap("n", "<esc>", "<cmd>noh<cr>", {})
vim.api.nvim_set_keymap("i", "jk", "<esc>", {})
vim.api.nvim_set_keymap("i", "kj", "<esc>", {})
vim.api.nvim_set_keymap("v", "p", "\"_dP", {})
vim.api.nvim_set_keymap("n", "<Tab>", "<cmd>bnext<cr>", {})
vim.api.nvim_set_keymap("n", "<S-Tab>", "<cmd>bprev<cr>", {})
vim.api.nvim_set_keymap("n", "<C-h>", "<C-w>h", {})
vim.api.nvim_set_keymap("n", "<C-j>", "<C-w>j", {})
vim.api.nvim_set_keymap("n", "<C-k>", "<C-w>k", {})
vim.api.nvim_set_keymap("n", "<C-l>", "<C-w>l", {})
vim.api.nvim_set_keymap("n", "<C-Up>", "<cmd>resize +2<cr>", {})
vim.api.nvim_set_keymap("n", "<C-Down>", "<cmd>resize -2<cr>", {})
vim.api.nvim_set_keymap("n", "<C-Left>", "<cmd>vertical resize +2<cr>", {})
vim.api.nvim_set_keymap("n", "<C-Right>", "<cmd>vertical resize -2<cr>", {})
vim.api.nvim_set_keymap("v", ">", ">gv", {})
return vim.api.nvim_set_keymap("v", "<", "<gv", {})