local _2afile_2a = "fnl/core/maps.fnl"
vim.g["mapleader"] = " "
vim.keymap.set({"n"}, "<C-z>", "<Nop>", {})
vim.keymap.set({"n"}, "Q", "<Nop>", {})
vim.keymap.set({"n"}, ";", ":", {})
vim.keymap.set({"n"}, "ww", "<cmd>w<cr>", {})
vim.keymap.set({"n"}, "ZZ", "<cmd>wqa<cr>", {})
vim.keymap.set({"n"}, "<esc>", "<cmd>noh<cr>", {})
vim.keymap.set({"i"}, "jk", "<esc>", {})
vim.keymap.set({"i"}, "kj", "<esc>", {})
vim.keymap.set({"v"}, "p", "\"_dP", {})
vim.keymap.set({"n"}, "<Tab>", "<cmd>bnext<cr>", {})
vim.keymap.set({"n"}, "<S-Tab>", "<cmd>bprev<cr>", {})
vim.keymap.set({"n"}, "<C-h>", "<C-w>h", {})
vim.keymap.set({"n"}, "<C-j>", "<C-w>j", {})
vim.keymap.set({"n"}, "<C-k>", "<C-w>k", {})
vim.keymap.set({"n"}, "<C-l>", "<C-w>l", {})
vim.keymap.set({"n"}, "<C-Up>", "<cmd>resize +2<cr>", {})
vim.keymap.set({"n"}, "<C-Down>", "<cmd>resize -2<cr>", {})
vim.keymap.set({"n"}, "<C-Left>", "<cmd>vertical resize +2<cr>", {})
vim.keymap.set({"n"}, "<C-Right>", "<cmd>vertical resize -2<cr>", {})
vim.keymap.set({"v"}, ">", ">gv", {})
return vim.keymap.set({"v"}, "<", "<gv", {})